package com.rapidreceipt.invoice;

import com.rapidreceipt.customer.Customer;
import com.rapidreceipt.user.User;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * The central document in RapidReceipt — an invoice or receipt issued
 * by a business owner (User) to one of their customers.
 *
 * Key design decisions:
 * - CascadeType.ALL on items: when an Invoice is saved, Hibernate automatically
 *   saves all its InvoiceItems. When an Invoice is deleted, items are deleted too.
 * - orphanRemoval = true: if you remove an item from the items list in Java
 *   and save, Hibernate will DELETE that row from the DB. This keeps the collection
 *   and the DB perfectly in sync without manual delete calls.
 * - subtotal / discount / total are stored (denormalised) rather than computed
 *   on the fly. This is intentional for financial records: amounts must not
 *   change if prices change in the future. Store the final agreed numbers.
 * - invoiceNumber must be unique across the platform. The InvoiceService will
 *   generate these (e.g. "RR-2024-00042") using atomic DB sequences.
 * - issueDate / dueDate use LocalDate (date only, no time component) since
 *   invoices are dated by calendar day, not by exact timestamp.
 * - @UpdateTimestamp stamps updatedAt on every save, useful for sync.
 */
@Entity
@Table(name = "invoices")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"user", "customer", "items"})
public class Invoice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The business owner who issued this invoice. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** The client this invoice is addressed to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    /**
     * Human-readable unique invoice number, e.g. "RR-2024-00042".
     * Generated by InvoiceService — never auto-generated by the DB.
     */
    @Column(nullable = false, unique = true, length = 50)
    private String invoiceNumber;

    @Column(nullable = false)
    private LocalDate issueDate;

    /** Null for receipts — payment has already been made. */
    private LocalDate dueDate;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    @Builder.Default
    private DocumentType documentType = DocumentType.INVOICE;

    /**
     * The line items on this invoice.
     * CascadeType.ALL + orphanRemoval = true means the items collection
     * is the single source of truth — add/remove from the list, save the Invoice.
     */
    @OneToMany(mappedBy = "invoice", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<InvoiceItem> items = new ArrayList<>();

    /** Pre-discount total of all line items (qty × price summed). */
    @Column(nullable = false, precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal subtotal = BigDecimal.ZERO;

    /** Flat or percentage discount — stored as the actual amount deducted. */
    @Column(nullable = false, precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal discount = BigDecimal.ZERO;

    /** Final amount payable: subtotal - discount. */
    @Column(nullable = false, precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal total = BigDecimal.ZERO;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Automatically updated by Hibernate on every save/merge. */
    @UpdateTimestamp
    @Column(nullable = false)
    private LocalDateTime updatedAt;
}
